apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres
  storageClassName: standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: NodePort   

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: saurabhjainwal/node-k8s-postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /data/postgres
          resources:
            limits:
              cpu: ".5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          # envFrom:
          # - secretRef:
          #     name: postgres-secret  
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-pvc