# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secret
# type: Opaque
# data:
#   POSTGRES_USER: cG9zdGdyZXM=
#   POSTGRES_PASSWORD: WERKMmpKMW1wNU9LS1F3NQ==
#   POSTGRES_DB: cG9zdGdyZXM=
#   POSTGRES_HOST_AUTH_METHOD: dHJ1c3Q=