table:
  name: products
  schema: products
array_relationships:
  - name: carts_products
    using:
      foreign_key_constraint_on:
        column: product_id
        table:
          name: carts_products
          schema: public
